services:
  - type: web
    name: sports-reels
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip ffmpeg
      pip3 install -r requirements.txt
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: true