services:
  - type: web
    name: sports-reels
    env: node
    repo: https://github.com/g-h-0-S-t/sports-reels
    buildCommand: |
      npm install
      pip3 install -r requirements.txt
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        fromService:
          name: sports-reels
          type: secret
      - key: NEXT_PUBLIC_APP_URL
        fromService:
          name: sports-reels
          type: secret
      - key: GITHUB_TOKEN
        fromService:
          name: sports-reels
          type: secret
      - key: UNSPLASH_ACCESS_KEY
        fromService:
          name: sports-reels
          type: secret